//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankh.Scc {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ankh.Scc.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add to Sub&amp;version.
        /// </summary>
        internal static string AddToSubversionCommandName {
            get {
                return ResourceManager.GetString("AddToSubversionCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Checking Out Project.
        /// </summary>
        internal static string CheckingOutProject {
            get {
                return ResourceManager.GetString("CheckingOutProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File Merge Completed?.
        /// </summary>
        internal static string MergeCompleted {
            get {
                return ResourceManager.GetString("MergeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The path &apos;{0}&apos; is currently blocked by subversion; do you have a file with a case-only-different name?.
        /// </summary>
        internal static string PathXBlocked {
            get {
                return ResourceManager.GetString("PathXBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The path &apos;{0}&apos; is in a subversion administrative area. This file shouldn&apos;t be added to subversion..
        /// </summary>
        internal static string SvnPathXBlocked {
            get {
                return ResourceManager.GetString("SvnPathXBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This file is marked as Conflicted..
        /// </summary>
        internal static string ToolTipConflict {
            get {
                return ResourceManager.GetString("ToolTipConflict", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This directory does not exist on disk. Instead there is a file with the same name.
        /// </summary>
        internal static string ToolTipDirObstructed {
            get {
                return ResourceManager.GetString("ToolTipDirObstructed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This file does not exist on disk..
        /// </summary>
        internal static string ToolTipDoesNotExist {
            get {
                return ResourceManager.GetString("ToolTipDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This file does not exist on disk. Instead there is a directory with the same name.
        /// </summary>
        internal static string ToolTipFileObstructed {
            get {
                return ResourceManager.GetString("ToolTipFileObstructed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This file is explicitly ignored by subversion..
        /// </summary>
        internal static string ToolTipIgnored {
            get {
                return ResourceManager.GetString("ToolTipIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You have exclusively locked this file..
        /// </summary>
        internal static string ToolTipLocked {
            get {
                return ResourceManager.GetString("ToolTipLocked", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This file is modified.
        /// </summary>
        internal static string ToolTipModified {
            get {
                return ResourceManager.GetString("ToolTipModified", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This file must be locked before it can be edited..
        /// </summary>
        internal static string ToolTipMustLock {
            get {
                return ResourceManager.GetString("ToolTipMustLock", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Subversion detected an unsupported working copy version while checking the status of &apos;{0}&apos;. Most likely you upgraded another Subversion client (e.g. TortoiseSVN or the SVN client) to a newer version without upgrading your AnkhSVN. Please visit http://ankhsvn.net/ to find out about newer AnkhSVN versions supporting this Working Copy.
        ///
        ///Most likely AnkhSVN will not work correctly on this and other upgraded working copies until you upgrade to a newer version..
        /// </summary>
        internal static string UnsupportedWorkingCopyFound {
            get {
                return ResourceManager.GetString("UnsupportedWorkingCopyFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Subversion detected a working copy that needs an explicit upgrade in &apos;{0}&apos;. 
        ///
        ///While this working copy is not upgraded all files in this working copy will appear as new. 
        ///
        ///When a working copy is upgraded it can no longer be used by Subversion clients that weren&apos;t designed for this (or later) working copy formats.
        ///
        ///Further working copy upgrade required warnings are suppressed until after you restart Visual Studio or upgrade a working copy..
        /// </summary>
        internal static string UpgradeRequired {
            get {
                return ResourceManager.GetString("UpgradeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your external merge tool saved &apos;{0}&apos;.
        ///Would you like to mark this conflicted file as resolved?.
        /// </summary>
        internal static string YourMergeToolSavedXWouldYouLikeItMarkedAsResolved {
            get {
                return ResourceManager.GetString("YourMergeToolSavedXWouldYouLikeItMarkedAsResolved", resourceCulture);
            }
        }
    }
}
